### ISSUE TITLE
Lack of transient scrollbars

### ISSUE THREAD

**Issue by ripefig** [FedoraQt/adwaita-qt#112]
See Kvantum for contrast

![image](https://user-images.githubusercontent.com/45201036/60533618-b72d2880-9d08-11e9-8674-79524194a18f.png)

**Comment by grulja** [comment]
I'm not sure what you mean. Can you please highlight problematic part? It would also be nice to have a comparison to a gtk app, not to Kvantum, as the theme targets to look like adwaita.

**Comment by ripefig** [comment]
The scrollbar should disappear when the mouse isn't hovering over the relevant area. It should not be visible at all times in other words.

**Comment by grulja** [comment]
Actually, when I run a gtk app, the scrollbar is visible all the time, it just changes width and the background hides, but the scrollbar handle is always visible. I also seem to have wrong scrollbar handle color.

**Comment by grulja** [comment]
Should be somewhat fixed with https://github.com/FedoraQt/adwaita-qt/commit/bca5e3daff0a9c1b5fa05cbc888397ddeac039a8 and with https://github.com/FedoraQt/adwaita-qt/commit/cd0bd6efe3392c7fc3cd0d72411a766734728431.

The only issue there is that the hover effect over the scrollbar handle is shown even if you move over   rest of the scrollbar area. Unfortunately it's Qt telling me that and I would need to reimplement some other parts. I don't think it's a major issue for now.
