### ISSUE TITLE
Provide more detailed instructions for how to use this theme under GNOME

### ISSUE THREAD

**Issue by jurf** [FedoraQt/adwaita-qt#24]
Seriously, I still can't get it straight. I know how to change the Qt4 theme thru `qtconfig-qt4`, but they still show icons in menus and buttons. And I tried setting the Qt5 theme with `qt5ct`, and with these variables, which I found somewhere, no documentation whatsoever:

```
export QT_QPA_PLATFORMTHEME=qt5ct
```

But I still can't get the colour scheme to work. What configuration do you have?

Thanks for the great work though. The last commits were superb!

**Comment by MartinBriza** [comment]
Yeah, in Qt5 the situation gets a tad worse. We have a Qt patch in Fedora setting Adwaita to be used by default in GNOME instead of the GTK+/Qt theme engine but that's not exactly a clean solution, especially since it doesn't allow the user to modify the theme to his liking.
Anyway, I'm investigating this at this moment - I'll put something up when I find something.

Also, I'd like to thank you for all these bug reports, they are insanely helpful! I'd not be able to find all these issues myself.

**Comment by DoctorJellyface** [comment]
What about having the GNOME tweak tool handle Qt theming too, as KDE does with GTK?

> Also, I'd like to thank you for all these bug reports, they are insanely helpful! I'd not be able to find all these issues myself.

Oh, you. \*blushes\*

**Comment by DoctorJellyface** [comment]
Btw, could you make a new release with d0ef2e4 so I can change the AUR package to use it instead of master?

**Comment by mitya57** [comment]
I think no instructions are needed in GNOME 3.20+, if qgnomeplatform theme is installed.
See GNOME/gnome-session@971baf2e225abc5a.

**Comment by MartinBriza** [comment]
Newer releases of qgnomeplatform now use the "gnome" plugin name which overrides the built-in gnome platform theme. So as long as you have qgnomeplatform, you should be okay.

**Comment by pacho2** [comment]
Indeed, it works nice as soon as qgnomeplatform is installed :D

**Comment by grulja** [comment]
This theme will be used by default when [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform) is installed, if not, you can follow instructions mentioned in README.
